"""Generate the firmware's model headers from the INT8 .tflite + edge artifacts.

Two headers land in edge/include/ (the PlatformIO project):

  • model.h       — the .tflite flatbuffer as a C byte array (TFLM consumes the
                    model straight from flash; alignas(16) per TFLM guidance).
  • model_meta.h  — everything the firmware needs AROUND the model: the served
                    decision threshold (from the training checkpoint), the
                    6-channel z-score stats (the model expects standardized
                    input), and the edge_model_version string heartbeats report.

Unlike the .tflite conversion itself (Linux-only toolchain), this script runs
anywhere — it only reads bytes + JSON (+ the checkpoint for the threshold). So
after a CI/Docker run produces convlstm_tiny_int8.tflite, the headers can be
regenerated on Windows.

    python scripts/tflite_to_header.py                       # default paths
    python scripts/tflite_to_header.py --tflite path.tflite --out-dir ../edge/include
"""
from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path

ML_ROOT = Path(__file__).resolve().parents[1]


def _env_path(var: str, default: Path) -> Path:
    return Path(os.environ.get(var) or default)


DEFAULT_EDGE_DIR = _env_path("FG_EDGE_ARTIFACT_DIR", ML_ROOT / "artifacts" / "edge")
DEFAULT_OUT_DIR = _env_path("FG_FIRMWARE_INCLUDE_DIR", ML_ROOT.parent / "edge" / "include")
DEFAULT_MODEL_VERSION = "convlstm-tiny-int8-v0.2"

_GENERATED_BANNER = (
    "// GENERATED by ml/scripts/tflite_to_header.py — DO NOT EDIT BY HAND.\n"
    "// Regenerate after every quantize run; the threshold and stats MUST match\n"
    "// the checkpoint the .tflite was converted from (train == serve).\n"
)


def emit_model_header(tflite_path: Path, out_path: Path) -> int:
    """Write the .tflite flatbuffer as edge/include/model.h. Returns byte count."""
    data = Path(tflite_path).read_bytes()
    lines = [
        _GENERATED_BANNER,
        f"// source: {Path(tflite_path).name} ({len(data)} bytes, "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')})",
        "#pragma once",
        "#include <cstdint>",
        "",
        "// Defined: the real model is present (inference.cpp refuses the placeholder).",
        "#define FG_MODEL_GENERATED 1",
        "",
        f"constexpr unsigned int g_fall_model_len = {len(data)};",
        "alignas(16) const uint8_t g_fall_model[] = {",
    ]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i: i + 12])
        lines.append(f"    {chunk},")
    lines += ["};", ""]
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    return len(data)


def emit_meta_header(
    ckpt_path: Path,
    channel_stats_path: Path,
    out_path: Path,
    model_version: str = DEFAULT_MODEL_VERSION,
) -> dict:
    """Write threshold + channel stats + version as edge/include/model_meta.h."""
    import torch  # local import: header emission for a ready .tflite shouldn't need TF

    ck = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    threshold = float(ck["threshold"])
    stats = json.loads(Path(channel_stats_path).read_text())
    mean, std = stats["mean"], stats["std"]
    assert len(mean) == 6 and len(std) == 6, "channel stats must be length-6"

    def carr(vals: list[float]) -> str:
        return ", ".join(f"{v:.8f}f" for v in vals)

    out = f"""{_GENERATED_BANNER}#pragma once

// The probability threshold picked at training time (recall-floor operating
// point). The edge fires — starts the grace period — when sigmoid(logit) >= it.
constexpr float FG_EDGE_THRESHOLD = {threshold:.6f}f;

// Reported in every heartbeat; the gateway compares it against the rollout
// target (the poor man's OTA check until real OTA ships, PLAN Phase 31).
#define FG_EDGE_MODEL_VERSION "{model_version}"

// Global per-channel z-score (ax, ay, az, wx, wy, wz). The model was trained on
// standardized windows, so the firmware standardizes BEFORE quantizing input.
constexpr float FG_CHANNEL_MEAN[6] = {{{carr(mean)}}};
constexpr float FG_CHANNEL_STD[6]  = {{{carr(std)}}};
"""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out)
    return {"threshold": threshold, "model_version": model_version}


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description="Emit firmware model headers from edge artifacts.")
    p.add_argument("--tflite", type=Path, default=DEFAULT_EDGE_DIR / "convlstm_tiny_int8.tflite")
    p.add_argument("--ckpt", type=Path, default=DEFAULT_EDGE_DIR / "convlstm_tiny_fp32.pt")
    p.add_argument("--channel-stats", type=Path, default=DEFAULT_EDGE_DIR / "channel_stats.json")
    p.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    p.add_argument("--model-version", default=DEFAULT_MODEL_VERSION)
    args = p.parse_args(argv)

    n = emit_model_header(args.tflite, args.out_dir / "model.h")
    meta = emit_meta_header(args.ckpt, args.channel_stats, args.out_dir / "model_meta.h",
                            args.model_version)
    print(f"wrote {args.out_dir / 'model.h'} ({n / 1024:.1f} KB flatbuffer)")
    print(f"wrote {args.out_dir / 'model_meta.h'} (threshold {meta['threshold']:.4f}, "
          f"version {meta['model_version']})")


if __name__ == "__main__":
    main()
