// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp88rQOi9IsiPbDqPERZ67zqD6vqe4WRo',
    appId: '1:862269614644:web:b506a8efa172144041b861',
    messagingSenderId: '862269614644',
    projectId: 'fall-detection-app-3e4b0',
    authDomain: 'fall-detection-app-3e4b0.firebaseapp.com',
    storageBucket: 'fall-detection-app-3e4b0.firebasestorage.app',
    measurementId: 'G-DS3K43SNDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhdCJDPcqWGdAumt2m82CpOnivqCC_VfU',
    appId: '1:862269614644:android:daa6add8e352510541b861',
    messagingSenderId: '862269614644',
    projectId: 'fall-detection-app-3e4b0',
    storageBucket: 'fall-detection-app-3e4b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6nAlEi1WqOGsuc3e-PG7GEBf3kt8u2sc',
    appId: '1:862269614644:ios:a1281019337adf3641b861',
    messagingSenderId: '862269614644',
    projectId: 'fall-detection-app-3e4b0',
    storageBucket: 'fall-detection-app-3e4b0.firebasestorage.app',
    iosBundleId: 'com.falldetection.fallDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6nAlEi1WqOGsuc3e-PG7GEBf3kt8u2sc',
    appId: '1:862269614644:ios:a1281019337adf3641b861',
    messagingSenderId: '862269614644',
    projectId: 'fall-detection-app-3e4b0',
    storageBucket: 'fall-detection-app-3e4b0.firebasestorage.app',
    iosBundleId: 'com.falldetection.fallDetectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp88rQOi9IsiPbDqPERZ67zqD6vqe4WRo',
    appId: '1:862269614644:web:6590bea5c091da5341b861',
    messagingSenderId: '862269614644',
    projectId: 'fall-detection-app-3e4b0',
    authDomain: 'fall-detection-app-3e4b0.firebaseapp.com',
    storageBucket: 'fall-detection-app-3e4b0.firebasestorage.app',
    measurementId: 'G-Q0SQ02ERBG',
  );
}
