// PLACEHOLDER — regenerated by ml/scripts/tflite_to_header.py alongside model.h.
// Values below are REAL (current checkpoint ml/artifacts/edge/convlstm_tiny_fp32.pt
// + channel_stats.json) so review and unit math are meaningful; the generator
// overwrites them on every quantize run to keep train == serve.
#pragma once

// The probability threshold picked at training time (recall-floor operating
// point). The edge fires — starts the grace period — when sigmoid(logit) >= it.
constexpr float FG_EDGE_THRESHOLD = 0.113295f;

// Reported in every heartbeat; the gateway compares it against the rollout
// target (the poor man's OTA check until real OTA ships, PLAN Phase 31).
#define FG_EDGE_MODEL_VERSION "convlstm-tiny-int8-v0.2"

// Global per-channel z-score (ax, ay, az, wx, wy, wz). The model was trained on
// standardized windows, so the firmware standardizes BEFORE quantizing input.
constexpr float FG_CHANNEL_MEAN[6] = {-4.13988781f, -3.34661055f, 2.90280271f,
                                      0.00117046f, 0.00779755f, -0.02610017f};
constexpr float FG_CHANNEL_STD[6] = {6.25121260f, 5.15389824f, 5.32329369f,
                                     1.59352374f, 1.13252103f, 1.20393622f};
